"""
Extrae cookies de Chrome directamente de su base de datos local.
Genera un archivo netscape cookies.txt para uso con yt-dlp.

Windows: C:/Users/andre/AppData/Local/Google/Chrome/User Data/Default/Network/Cookies
Usa DPAPI para descifrar las cookies v10+.
"""
import os
import sys
import json
import base64
import sqlite3
import shutil
from pathlib import Path

try:
    import win32crypt
    from Crypto.Cipher import AES
except ImportError:
    print("Faltan dependencias. Ejecuta: pip install pywin32 pycryptodome")
    sys.exit(1)

CHROME_USER_DATA = Path(os.path.expanduser('~/AppData/Local/Google/Chrome/User Data'))
LOCAL_STATE = CHROME_USER_DATA / 'Local State'
OUTPUT = Path('D:/Herramientas/SOLER/cookies.txt')

DOMAINS_OF_INTEREST = ['systeme.io', 'autotech', 'hptuners', 'vimeo.com', 'vimeo']


def get_encryption_key():
    """Extrae la master key de Local State y la descifra con DPAPI."""
    with open(LOCAL_STATE, 'r', encoding='utf-8') as f:
        state = json.load(f)
    encrypted_key = base64.b64decode(state['os_crypt']['encrypted_key'])
    # Quita prefijo 'DPAPI'
    encrypted_key = encrypted_key[5:]
    # DPAPI decrypt
    decrypted = win32crypt.CryptUnprotectData(encrypted_key, None, None, None, 0)[1]
    return decrypted


def decrypt_cookie_value(encrypted_value, key):
    """Descifra una cookie cifrada con AES-GCM (v10)."""
    try:
        if encrypted_value[:3] == b'v10' or encrypted_value[:3] == b'v11':
            nonce = encrypted_value[3:3+12]
            ciphertext = encrypted_value[3+12:-16]
            tag = encrypted_value[-16:]
            cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
            return cipher.decrypt_and_verify(ciphertext, tag).decode('utf-8', errors='replace')
        else:
            # Old format - DPAPI directly
            return win32crypt.CryptUnprotectData(encrypted_value, None, None, None, 0)[1].decode('utf-8', errors='replace')
    except Exception as e:
        return ''


def extract_cookies(profile_name='Default'):
    cookies_db = CHROME_USER_DATA / profile_name / 'Network' / 'Cookies'
    if not cookies_db.exists():
        print(f"[ERR] No se encontro {cookies_db}")
        return []

    # Copiar temporalmente para no chocar con Chrome
    temp = Path('C:/Users/andre/AppData/Local/Temp/soler_cookies_temp.db')
    shutil.copy2(cookies_db, temp)

    key = get_encryption_key()

    conn = sqlite3.connect(temp)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT host_key, name, path, expires_utc, is_secure, is_httponly,
               encrypted_value, value, samesite
        FROM cookies
    """)

    result = []
    for row in cursor.fetchall():
        host, name, path, expires_utc, secure, httponly, enc_val, plain_val, samesite = row
        # Filter interesting domains
        if not any(d in host.lower() for d in DOMAINS_OF_INTEREST):
            continue
        value = plain_val
        if enc_val:
            value = decrypt_cookie_value(enc_val, key)
        if not value:
            continue
        # Chrome timestamp -> unix (desde 1601)
        expires_unix = max(0, int(expires_utc / 1_000_000) - 11644473600) if expires_utc else 0
        result.append({
            'host': host,
            'subdomains': 'TRUE' if host.startswith('.') else 'FALSE',
            'path': path,
            'secure': 'TRUE' if secure else 'FALSE',
            'expires': expires_unix,
            'name': name,
            'value': value,
        })

    conn.close()
    temp.unlink()
    return result


def write_netscape(cookies, output):
    lines = ['# Netscape HTTP Cookie File', '# Generated by SOLER', '']
    for c in cookies:
        lines.append(f"{c['host']}\t{c['subdomains']}\t{c['path']}\t{c['secure']}\t{c['expires']}\t{c['name']}\t{c['value']}")
    output.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main():
    # Probar perfiles
    profiles = [p.name for p in CHROME_USER_DATA.iterdir() if (p / 'Cookies').exists() or (p / 'Network/Cookies').exists()]
    print(f"Perfiles Chrome detectados: {profiles}")

    all_cookies = []
    for profile in profiles:
        print(f"\nExtrayendo de perfil: {profile}")
        cookies = extract_cookies(profile)
        print(f"  {len(cookies)} cookies de dominios de interes")
        all_cookies.extend(cookies)

    # Deduplicar
    seen = set()
    unique = []
    for c in all_cookies:
        k = (c['host'], c['name'], c['path'])
        if k not in seen:
            seen.add(k)
            unique.append(c)

    write_netscape(unique, OUTPUT)
    print(f"\n[OK] {len(unique)} cookies escritas a {OUTPUT}")

    # Resumen por dominio
    from collections import Counter
    by_host = Counter(c['host'] for c in unique)
    print("\nCookies por dominio:")
    for host, n in by_host.most_common():
        print(f"  {host}: {n}")


if __name__ == "__main__":
    main()
